### ISSUE TITLE
Evaluation error on COCO dataset

### ISSUE THREAD

**Issue by ml-ai-cv** [microsoft/GLIP#88]
Hello,

I am trying to use the evaluation code for prediction on COCO 2017 dataset for replicating/measuring  zero-shot performance on coco2017/

Steps I followed:

1. created the DATASET folder with COCO data from https://cocodataset.org/#download in this format

**val2017**
DATASET/coco/val2017
DATASET/coco/annotations/instances_val2017.json

**test2017**
DATASET/coco/test2017
DATASET/coco/annotations/image_info_test-dev2017.json

2. created MODEL folder and downloaded these checkpoint files in it
mkdir MODEL
wget https://penzhanwu2bbs.blob.core.windows.net/data/GLIPv1_Open/models/swin_tiny_patch4_window7_224.pth -O swin_tiny_patch4_window7_224.pth
wget https://penzhanwu2bbs.blob.core.windows.net/data/GLIPv1_Open/models/swin_large_patch4_window12_384_22k.pth -O swin_large_patch4_window12_384_22k.pth

3. Using the model zoo (table) I downloaded this checkpoint file for GLIP-L (https://penzhanwu2bbs.blob.core.windows.net/data/GLIPv1_Open/models/glip_large_model.pth) in MODEL folder

4. created output folder in GLIP folder

5. then I gave this command

python tools/test_grounding_net.py --config-file ./configs/pretrain/glip_Swin_L.yaml --weight ./MODEL/glip_large_model.pth TEST.IMS_PER_BATCH 1 MODEL.DYHEAD.SCORE_AGG "MEAN" TEST.EVAL_TASK detection MODEL.DYHEAD.FUSE_CONFIG.MLM_LOSS False OUTPUT_DIR output

After running this evaluation command I am getting this error

The combined datasets are: ('coco_2017_val',).
loading annotations into memory...
Done (t=0.38s)
creating index...
index created!
coco_2017_val has the 5000 data points COCODataset
2023-04-18 22:53:06,543 maskrcnn_benchmark.inference INFO: Start evaluation on coco_2017_val dataset(5000 images).
banner. blanket. branch. bridge. building-other. bush. cabinet. cage. cardboard. carpet. ceiling-other. ceiling-tile. cloth. clothes. clouds. counter. cupboard. curtain. desk-stuff. dirt. door-stuff. fence. floor-marble. floor-other. floor-stone. floor-tile. floor-wood. flower. fog. food-other. fruit. furniture-other. grass. gravel. ground-other. hill. house. leaves. light. mat. metal. mirror-stuff. moss. mountain. mud. napkin. net. paper. pavement. pillow. plant-other. plastic. platform. playingfield. railing. railroad. river. road. rock. roof. rug. salad. sand. sea. shelf. sky-other. skyscraper. snow. solid-other. stairs. stone. straw. structural-other. table. tent. textile-other. towel. tree. vegetable. wall-brick. wall-concrete. wall-other. wall-panel. wall-stone. wall-tile. wall-wood. water-other. waterdrops. window-blind. window-other. wood. other
All queries ['banner. blanket. branch. bridge. building-other. bush. cabinet. cage. cardboard. carpet. ceiling-other. ceiling-tile. cloth. clothes. clouds. counter. cupboard. curtain. desk-stuff. dirt. door-stuff. fence. floor-marble. floor-other. floor-stone. floor-tile. floor-wood. flower. fog. food-other. fruit. furniture-other. grass. gravel. ground-other. hill. house. leaves. light. mat. metal. mirror-stuff. moss. mountain. mud. napkin. net. paper. pavement. pillow. plant-other. plastic. platform. playingfield. railing. railroad. river. road. rock. roof. rug. salad. sand. sea. shelf. sky-other. skyscraper. snow. solid-other. stairs. stone. straw. structural-other. table. tent. textile-other. towel. tree. vegetable. wall-brick. wall-concrete. wall-other. wall-panel. wall-stone. wall-tile. wall-wood. water-other. waterdrops. window-blind. window-other. wood. other']
  0%|                                                                                                                                      | 0/5000 [00:00<?, ?it/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
  0%|                                                                                                                                      | 0/5000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tools/test_grounding_net.py", line 222, in <module>
    main()
  File "tools/test_grounding_net.py", line 205, in main
    inference(
  File "/GLIP/maskrcnn_benchmark/engine/inference.py", line 450, in inference
    for i, batch in enumerate(_iterator):
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1193, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/GLIP/maskrcnn_benchmark/data/datasets/coco.py", line 256, in __getitem__
    img, target = self.transforms(img, target)
  File "/GLIP/maskrcnn_benchmark/data/transforms/transforms.py", line 70, in __call__
    image, target = t(image, target)
  File "/GLIP/maskrcnn_benchmark/data/transforms/transforms.py", line 126, in __call__
    target = target.resize(new_size)
  File "/GLIP/maskrcnn_benchmark/structures/bounding_box.py", line 143, in resize
    v = v.resize(size, *args, **kwargs)
  File "/GLIP/maskrcnn_benchmark/structures/segmentation_mask.py", line 186, in resize
    scaled.append(polygon.resize(size, *args, **kwargs))
  File "/GLIP/maskrcnn_benchmark/structures/segmentation_mask.py", line 118, in resize
    p = poly.clone()
AttributeError: 'str' object has no attribute 'clone'

Please let me know  how to remove this error. 

I appreciate your help.

**Comment by tisharSinha** [comment]
I also get the same warning and the code runs for hours with doing anything after this:
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

**Comment by whhong5** [comment]
I met the same error.

**Comment by sharad5** [comment]
Same Error while trying to run a COCO Formatted Custom Dataset.
